run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - bodyclose
    - noctx
    - prealloc

linters-settings:
  govet:
    enable-all: true
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
